DROP SEQUENCE MonitorPoint_seq START WITH 1 INCREMENT BY 1;
DROP SEQUENCE ComponT_seq START WITH 1 INCREMENT BY 10;
DROP SEQUENCE Assembly_seq START WITH 1 INCREMENT BY 1;
DROP SEQUENCE BACIProperty_seq START WITH 1 INCREMENT BY 1;
DROP SEQUENCE  Component_seq START WITH 1 INCREMENT BY 1;
