CREATE SEQUENCE ComponT_seq START WITH 1 INCREMENT BY 10; 
CREATE SEQUENCE MonitorPoint_seq START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE Assembly_seq START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE BACIProperty_seq START WITH 1 INCREMENT BY 10;
CREATE SEQUENCE  Component_seq START WITH 1 INCREMENT BY 10;
